import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  metadataBase: new URL("https://www.venezuelanlegalservices.com"),
  title: {
    default: "Venezuelan Legal Services | Asilo, TPS, Permisos de Trabajo y Visas",
    template: "%s | Venezuelan Legal Services",
  },
  description:
    "Tu proceso legal, más claro que nunca. Orientación y preparación de documentos para Asilo, TPS, permisos de trabajo y otros trámites migratorios en EE.UU. Atención en español e inglés.",
  keywords: [
    "asilo político",
    "TPS",
    "permiso de trabajo",
    "EAD",
    "visas humanitarias",
    "visas estudiantiles",
    "abogados de inmigración",
    "servicios legales en español",
    "preparación de formularios",
    "asesoría migratoria",
  ],
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: "/",
    title: "Venezuelan Legal Services | Tu proceso legal, más claro que nunca",
    description:
      "Apoyo confiable para tu proceso de asilo, TPS, permisos de trabajo y más. Soporte por WhatsApp y acceso seguro a tus documentos.",
    siteName: "Venezuelan Legal Services",
    images: [
      {
        url: "/og-vls.jpg",
        width: 1200,
        height: 630,
        alt: "Venezuelan Legal Services — Tu proceso legal, más claro que nunca",
      },
    ],
    locale: "es_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Venezuelan Legal Services",
    description:
      "Asilo, TPS, permisos de trabajo y más. Atención en español. Soporte por WhatsApp.",
    images: ["/og-vls.jpg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      // use quoted kebab-case keys:
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  category: "legal",
};